### ISSUE TITLE
Upgrade Asp.Net Core 1.0.0

### ISSUE THREAD

**Issue by fernandocode** [tonysneed/Demo.AspNetCore.EF6#5]
In Asp.Net Core 1.0.0 project the following problem occurs:

> Unable to determine the provider name is provider of factory type ‘System.Data.SqlClient.SqlClientFactory’. Make sure the provider que ADO.NET is installed or registered in the application config.

**Comment by tonysneed** [comment]
@fernandocode Thanks .. I will upgrade to 1.0 and see if the error occurs.

**Comment by tonysneed** [comment]
I upgraded the project to 1.0 RTM.  However, I did not receive the error you describe.  This may be helpful to you: http://stackoverflow.com/a/26907080 [edited].

**Comment by tonysneed** [comment]
@fernandocode Are you receiving this error with an exact clone of this repo? Or is it with your own project?

**Comment by fernandocode** [comment]
@tonysneed, exact clone. I think the problem must be related to something in my environment. Because a coworker tried to run the same repository project and its environment everything worked perfectly, and its development environment would be the same as mine, also being with Asp.Net 1.0.

I'll get investigate what's different in my environment that is causing the error. I will try to check the versions of toolings and SQL Server Provider installed in both environments.

If I find some solution inform here. = /

**Comment by fernandocode** [comment]
I managed to solve the problem that happened in my environment, after checking the driver and installed providers in my environment that were different from my coworker environment and not succeed. I noticed that in some of the suggestions on my problem was to add a `web.config`configuration to `<DbProviderFactories>`, as [this issue](http://stackoverflow.com/a/31800310/2290538). But as in ASP.Net 1.0 Core projects there is no `web.config` I started looking for another way to get the same result was as follows:

In `DbConfig.cs` add line:  

> `SetProviderFactory("System.Data.SqlClient", System.Data.SqlClient.SqlClientFactory.Instance);`

Result class:

```
using System.Data.Entity;
using System.Data.Entity.SqlServer;

namespace Experimental.AspNetCore.EF6.Contexts
{
    public class DbConfig : DbConfiguration
    {
        public DbConfig()
        {
            SetProviderFactory("System.Data.SqlClient", System.Data.SqlClient.SqlClientFactory.Instance);
            SetProviderServices("System.Data.SqlClient", SqlProviderServices.Instance);
        }
    }
}
```

And add in section `dependecies` in `project.json`:

> `"System.Data.SqlClient": "4.1.0"`

Check that with this configuration the project is still running in your environment. Maybe you can add it to the official project.

> PS: I even set up a branch here but I could not submite it. =\

**Comment by tonysneed** [comment]
Glad you found a solution!  I suggest that you fork the repository, make your changes there, then paste a link to your forked repository here.

**Comment by fernandocode** [comment]
[Here's the fork in your repository with my solution to the problem](https://github.com/fernandocode/Demo.AspNetCore.EF6). Few changes that cost me some work time and research. = D
