### ISSUE TITLE
Update the Solution to support VS 2015 Update 3. Errors galore! Thank you.

### ISSUE THREAD

**Issue by crosehaascnc** [tonysneed/Demo.AspNetCore.EF6#6]

**Comment by tonysneed** [comment]
@crosehaascnc Can you please provide some info or a screen shot?

**Comment by crosehaascnc** [comment]
Just try and build with Visual Studio 2015 Update 3 – you’ll see the errors. They have to do with changes to DNX…

For a Delta, create a new .NETCore1.0 web application, and then spy the differences in the JSON settings files.

**Comment by tonysneed** [comment]
Actually, the repo has been updated, but you have to select the **migrate-1.0** [branch](https://github.com/tonysneed/Demo.AspNetCore.EF6/tree/migrate-1.0).

I updated the [blog post](https://blog.tonysneed.com/2016/01/22/ef6-asp-net-core-mvc6/) with a note to this effect.

**Comment by crosehaascnc** [comment]
Got it, thanks.
